/** Screenshots for the feature reference in `docs/features/` (#134).
 *
 *  ## Why this exists rather than `shot-matrix.mjs`
 *
 *  CLAUDE.md records how the site's documentation went wrong: *"Images decay
 *  loudly and prose decays quietly."* Loudly is the good half — a stale
 *  screenshot is visible. It is only good if the images are CHEAP to redo, or
 *  nobody redoes them and loud decay becomes permanent decay.
 *
 *  So every image in `docs/features/img/` is generated by this file from the
 *  running app and none is hand-placed. `npm run docs:shots` rebuilds all of
 *  them.
 *
 *  `shot-matrix.mjs` cannot be that tool. It is CLI-only (argv parsed at module
 *  scope, no exports), it shoots a 3-width matrix where docs want one width, it
 *  names files from the URL where docs want stable ids, and — the blocking one —
 *  **it has no clock control**. See DETERMINISM below.
 *
 *  It builds on `cdp.mjs`, which is importable and side-effect free, and the
 *  full-page capture below is the same wait-for-three-things logic
 *  `shot-matrix.mjs` uses, because that logic is the valuable part and getting
 *  it subtly different would produce cropped PNGs nobody notices.
 *
 *  ## DETERMINISM — the reason for the fixed date
 *
 *  Two clocks leak into the pixels:
 *
 *    - `Today.tsx` renders `now.toLocaleDateString(...)`, so every Today PNG
 *      carries the date it was shot.
 *    - `Log.tsx` seeds its meal-slot chip from `mealSlotFor()`, so the confirm,
 *      basket, portion, refused, dropped and correct stages render a DIFFERENT
 *      CHIP depending on the hour the tool ran.
 *
 *  Left alone that means every run rewrites every PNG, `git status` is
 *  permanently dirty, and a real change is invisible in the noise — which is
 *  the same "you cannot see the signal" failure the generated images exist to
 *  prevent.
 *
 *  So the clock is pinned to DOC_WHEN in the page (the `Shifted extends Date`
 *  trick `screencast.mjs` uses for `--at`, generalised to a whole datetime) AND
 *  the demo data is seeded for that same day. Both halves are required: pinning
 *  the clock alone would have the client ask `/api/day` for a date nothing was
 *  seeded against, and the app would correctly render an empty day.
 *
 *  ## ORDER — cookie BEFORE seed
 *
 *  Every INSERT in `seed-demo.mjs` is `SELECT <literals>, id FROM users ORDER BY
 *  createdAt LIMIT 1`. With no user row the SELECT matches nothing, **nothing is
 *  inserted, no error is raised**, and the script still prints "Seeded ...". So
 *  a fresh machine that seeds first gets a silent no-op and a set of screenshots
 *  of an empty app. `--seed` here mints the session first for that reason.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { connect, evaluate, launchChrome, openPage, settle, waitFor } from "./cdp.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "docs/features/img");
const WIDTH = 375; // build rule 6: the reference width, and the only one docs need.

/** The day the documentation lives on. It must be FIXED, and it must be the day
 *  the demo data is seeded for.
 *
 *  **It must also be a day `seed-demo.mjs` put a run on**, and that is not a
 *  detail. Runs land Mon/Wed/Fri/Sun and never on the seed's own last day, so an
 *  arbitrary date renders a budget meter with no earned extension — and the
 *  two-part meter is the single most important thing this documentation has to
 *  show (build rule 7). The first pick here was 2026-06-15, which produced a
 *  perfectly good screenshot of exactly the case the article is not about.
 *  2026-06-14 is a Sunday carrying a 690 kcal run.
 *
 *  19:30 puts `mealSlotFor()` in `dinner` and leaves seed-demo's
 *  deliberately-unlogged dinner unlogged, which is the more interesting Today.
 *  `assertSeeded()` below fails the run if either property stops holding. */
const DOC_DAY = "2026-06-14";
const DOC_WHEN = `${DOC_DAY}T19:30:00`;

const DEV_EMAIL = "dev@mymacros.local";
const DEV_PASSWORD = "dev-password-not-for-production";

/** id → what to render. `id` is the filename and the string an article cites,
 *  so it is stable across a URL change on purpose.
 *
 *  `auth: false` means the shot must NOT carry a cookie — the sign-in screens
 *  render the app instead if it does, which is a silent wrong-screenshot. */
export const MANIFEST = [
  // ── signed out ──
  { id: "signin", path: "/", auth: false },
  { id: "signin-fresh", path: "/#fresh", auth: false },
  { id: "signin-enrol", path: "/#enrol", auth: false },
  { id: "signin-enrol-keyboard", path: "/#enrol", auth: false, keyboard: 336 },

  // ── today ──
  { id: "today", path: "/" },
  { id: "today-saved", path: "/#saved" },
  { id: "today-swiped", path: "/#swiped" },
  { id: "today-editing", path: "/#editing" },
  { id: "today-offline", path: "/#offline" },
  { id: "today-failed", path: "/#failed" },

  // ── the log flow ──
  { id: "log-photo", path: "/log#photo", camera: true, settle: 1200 },
  { id: "log-photo-no-camera", path: "/log" },
  { id: "log-barcode", path: "/log#barcode", camera: true, settle: 1200 },
  { id: "log-text", path: "/log#text" },
  { id: "log-picks", path: "/log#picks", camera: true, settle: 1200 },
  { id: "log-note", path: "/log#note", camera: true, settle: 1200 },
  { id: "log-note-keyboard", path: "/log#note", camera: true, settle: 1200, keyboard: 336 },
  { id: "log-confirm", path: "/log#confirm" },
  { id: "log-portion", path: "/log#portion" },
  { id: "log-basket", path: "/log#basket" },
  { id: "log-dropped", path: "/log#dropped" },
  { id: "log-refused", path: "/log#refused" },
  { id: "log-correct", path: "/log#correct" },

  // ── trends, weight, settings, onboarding ──
  { id: "trends", path: "/trends" },
  { id: "trends-empty", path: "/trends#empty" },
  { id: "trends-sparse", path: "/trends#sparse" },
  { id: "trends-failed", path: "/trends#failed" },
  { id: "weight", path: "/weight" },
  { id: "weight-failed", path: "/weight#failed" },
  { id: "settings", path: "/settings" },
  { id: "settings-failed", path: "/settings#failed" },
  { id: "onboarding", path: "/onboarding" },
  { id: "onboarding-keyboard", path: "/onboarding", keyboard: 336 },

  // ── the light packs (build rule 4's own evidence) ──
  { id: "today-field-notes", path: "/", theme: "field-notes" },
  { id: "today-instrument", path: "/", theme: "instrument" },
];

const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);
const val = (f, d) => (argv.indexOf(f) >= 0 ? argv[argv.indexOf(f) + 1] : d);
const BASE = (val("--base", "http://localhost:5173") ?? "").replace(/\/$/, "");
const ONLY = val("--only", null);

/** Newest-mtime, never `find | head -1`. Two sqlite files exist on a machine
 *  that has ever changed `database_id`, and the abandoned one can be many
 *  migrations behind — `npm run db:studio` picks wrong for this reason. */
function d1File() {
  const dir = join(ROOT, ".wrangler/state/v3/d1/miniflare-D1DatabaseObject");
  if (!existsSync(dir)) return null;
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".sqlite"))
    .map((f) => join(dir, f));
  if (!files.length) return null;
  return files.sort((a, b) => statMtime(b) - statMtime(a))[0];
}
function statMtime(p) {
  return Number(execFileSync("stat", ["-f", "%m", p]).toString().trim());
}
const sql = (q) => execFileSync("sqlite3", [d1File(), q]).toString().trim();

async function mintCookie() {
  const body = JSON.stringify({ email: DEV_EMAIL, password: DEV_PASSWORD, name: "Dev" });
  // `trustedOrigins` derives from APP_URL, so Origin is required and must match
  // exactly or better-auth answers 403 INVALID_ORIGIN — a message that names no
  // port, which is why `npm run dev` is --strictPort.
  const headers = { "Content-Type": "application/json", Origin: BASE };
  for (const ep of ["sign-in", "sign-up"]) {
    const res = await fetch(`${BASE}/api/auth/${ep}/email`, { method: "POST", headers, body });
    const raw = res.headers.getSetCookie?.() ?? [];
    const hit = raw.find((c) => c.startsWith("better-auth.session_token="));
    if (hit) return hit.split(";")[0];
  }
  throw new Error(
    `could not mint a session at ${BASE}. Check the dev server is up, that .dev.vars ` +
      `has APP_URL=${BASE}, and that ALLOWED_EMAILS contains ${DEV_EMAIL}.`,
  );
}

/** `seed-demo.mjs` cannot produce one: `foldMeals` keys on `logged_at|slot`, and
 *  the seeder stamps its two breakfast rows one minute apart, so nothing folds.
 *  Every seeded timeline entry is therefore a single-item meal and `/#editing`
 *  — which opens the day's LARGEST entry — always renders the short sheet.
 *  A stage that shoots the easy case is worse than no stage, so the tall case
 *  is inserted here rather than left to chance. */
function seedMultiItemMeal() {
  const at = `${DOC_DAY}T23:10:00.000Z`;
  const rows = [
    ["Roast chicken thigh", 320, 28, 0, 22],
    ["Jasmine rice", 205, 4.3, 45, 0.4],
    ["Tenderstem broccoli", 55, 4.8, 7.2, 0.6],
    ["Chilli oil", 90, 0, 0, 10],
  ];
  sql(`DELETE FROM food_logs WHERE id LIKE 'doc-multi-%';`);
  rows.forEach(([name, kcal, p, c, f], i) => {
    sql(
      `INSERT INTO food_logs (id,user_id,logged_on,logged_at,meal_slot,name,kcal,protein_g,carbs_g,fat_g,source,confidence,edited)
       SELECT 'doc-multi-${i}', id, '${DOC_DAY}', '${at}', 'dinner', '${name}', ${kcal}, ${p}, ${c}, ${f}, 'photo', 'high', 0
       FROM users ORDER BY createdAt LIMIT 1;`,
    );
  });
}

/** Pinned in the page, not on the host: the host clock is shared with wrangler,
 *  and moving it would re-date rows the seeder just wrote. */
const clockScript = () => `(() => {
  const OFFSET = new Date(${JSON.stringify(DOC_WHEN)}).getTime() - Date.now();
  const Real = Date;
  class Shifted extends Real {
    constructor(...a) { a.length === 0 ? super(Real.now() + OFFSET) : super(...a); }
    static now() { return Real.now() + OFFSET; }
  }
  globalThis.Date = Shifted;
})();`;

async function main() {
  if (!existsSync(join(ROOT, "docs/features"))) {
    throw new Error("docs/features/ is missing — nothing to shoot for.");
  }
  mkdirSync(OUT_DIR, { recursive: true });

  const health = await fetch(`${BASE}/api/health`).then((r) => r.json());
  if (!health.ok) {
    throw new Error(`${BASE}/api/health is not ok: ${JSON.stringify(health)}. Run db:migrate.`);
  }

  const cookie = await mintCookie();
  const me = await fetch(`${BASE}/api/me`, { headers: { Cookie: cookie } });
  if (me.status !== 200) throw new Error(`session did not take: /api/me answered ${me.status}`);

  if (has("--seed")) {
    // --weeks first, then one-day: one-day DELETEs the day's rows and replaces
    // them with a richer set, so the reverse order throws that away.
    console.log(`seeding 12 weeks to ${DOC_DAY} …`);
    execFileSync("node", ["tools/seed-demo.mjs", "--weeks", "12", DOC_DAY], {
      cwd: ROOT,
      stdio: "inherit",
    });
    execFileSync("node", ["tools/seed-demo.mjs", DOC_DAY], { cwd: ROOT, stdio: "inherit" });
    seedMultiItemMeal();
    await assertSeeded(cookie);
  }

  const shots = ONLY ? MANIFEST.filter((s) => s.id === ONLY) : MANIFEST;
  if (!shots.length) throw new Error(`--only ${ONLY} matched nothing in the manifest`);

  const themed = [...new Set(shots.map((s) => s.theme ?? "night-athletic"))];
  const { proc, wsUrl } = await launchChrome(join(ROOT, ".doc-shots-profile"), [
    "--use-fake-ui-for-media-stream",
    "--use-fake-device-for-media-stream",
  ]);
  const cdp = await connect(wsUrl);
  let written = 0;
  try {
    for (const theme of themed) {
      // The flag alone cannot beat a signed-in profile: App.tsx applies
      // me.profile.theme when the profile lands. Set the row (build rule 4).
      sql(`UPDATE profiles SET theme='${theme}';`);
      for (const shot of shots.filter((s) => (s.theme ?? "night-athletic") === theme)) {
        await capture(cdp, shot, cookie);
        written++;
        console.log(`  ✓ ${shot.id}.png`);
      }
    }
    sql(`UPDATE profiles SET theme='night-athletic';`);
  } finally {
    await cdp.close();
    proc.kill();
  }
  console.log(`\n${written} shot(s) → docs/features/img/`);
}

/** Every INSERT in `seed-demo.mjs` targets `users ORDER BY createdAt LIMIT 1` —
 *  the OLDEST user, which is not necessarily the one this tool signs in as. On
 *  this machine there are nine user rows and `dev@` happens to be the oldest, so
 *  it works by luck. A machine where it isn't gets a silent no-op: the seed
 *  prints success, the screenshots render an empty app, and nothing says why.
 *
 *  So the pipeline asks the API, as the signed-in user, whether the day it is
 *  about to photograph actually has what the articles claim. Checking the
 *  database instead would prove the rows exist for SOMEBODY, which is the thing
 *  that is already true and not the thing in question. */
async function assertSeeded(cookie) {
  const res = await fetch(`${BASE}/api/day/${DOC_DAY}`, { headers: { Cookie: cookie } });
  if (res.status !== 200) {
    throw new Error(`GET /api/day/${DOC_DAY} answered ${res.status}, so this assertion proves nothing`);
  }
  const day = await res.json();

  const fail = (why) =>
    new Error(
      `${DOC_DAY} is not seeded for the signed-in user: ${why}. ` +
        `seed-demo.mjs writes to the OLDEST user row; this tool signs in as ${DEV_EMAIL}. ` +
        `If they differ, the seed is a silent no-op.`,
    );

  if (!day?.logs?.length) throw fail("no food logs came back");
  // Build rule 7's whole subject. Without a run the meter draws one length and
  // every screenshot of it argues the opposite of the article beside it.
  // The figure is `run.earned_kcal`, NOT a top-level `earned_kcal` — this
  // assertion read the latter on its first three runs and failed against a day
  // that was correctly seeded the whole time. A check that is wrong about the
  // shape it reads reports a defect that does not exist, which costs exactly
  // what a check that cannot fail costs, in the other direction.
  if (!day.run?.earned_kcal) {
    throw fail(`run.earned_kcal is ${day.run?.earned_kcal} — no run on this day`);
  }
  const folded = day.logs.filter((l) => l.logged_at === `${DOC_DAY}T23:10:00.000Z`);
  if (folded.length < 2) throw fail("the multi-item meal did not land, so /#editing is the short sheet");
  console.log(
    `  seeded: ${day.logs.length} logs, ${day.run.earned_kcal} kcal earned, ` +
      `${folded.length}-item meal for the tall edit sheet`,
  );
}

async function capture(cdp, shot, cookie) {
  const { targetId, sessionId } = await openPage(cdp);
  const s = sessionId;
  try {
    await cdp.send("Page.addScriptToEvaluateOnNewDocument", { source: clockScript() }, s);
    if (shot.keyboard) {
      const { keyboardScript } = await import("./cdp.mjs");
      await cdp.send(
        "Page.addScriptToEvaluateOnNewDocument",
        { source: keyboardScript(shot.keyboard, { paint: true }) },
        s,
      );
    }
    if (shot.auth !== false) {
      const [name, value] = cookie.split("=");
      await cdp.send(
        "Network.setCookie",
        { name, value, url: BASE, path: "/", httpOnly: true, sameSite: "Lax" },
        s,
      );
    }
    if (shot.camera) {
      await cdp.send(
        "Browser.grantPermissions",
        { origin: BASE, permissions: ["videoCapture"] },
        undefined,
      );
    }

    await cdp.send(
      "Emulation.setDeviceMetricsOverride",
      { width: WIDTH, height: 812, deviceScaleFactor: 2, mobile: true },
      s,
    );
    await navigateAndWait(cdp, s, `${BASE}${shot.path}`, shot);

    const height = await evaluate(
      cdp,
      s,
      "Math.max(document.documentElement.scrollHeight, document.body.scrollHeight, 812)",
    );
    await cdp.send(
      "Emulation.setDeviceMetricsOverride",
      { width: WIDTH, height: Math.ceil(height), deviceScaleFactor: 2, mobile: true },
      s,
    );
    await settle(cdp, s);

    const { data } = await cdp.send(
      "Page.captureScreenshot",
      { format: "png", captureBeyondViewport: false },
      s,
    );
    writeFileSync(join(OUT_DIR, `${shot.id}.png`), Buffer.from(data, "base64"));
  } finally {
    await cdp.send("Target.closeTarget", { targetId });
  }
}

/** The three waits, same as `shot-matrix.mjs`: React has mounted, the screen's
 *  own /api fetches have landed, and the height has stopped moving. Measuring
 *  once and shooting at it is what silently cropped every PNG in this repo
 *  before 2026-08-14. */
async function navigateAndWait(cdp, s, url, shot) {
  await cdp.send(
    "Page.addScriptToEvaluateOnNewDocument",
    {
      source: `(() => { let n = 0; const f = window.fetch;
        window.__inflight = () => n;
        window.fetch = (...a) => { n++; return f(...a).finally(() => { n--; }); };
      })();`,
    },
    s,
  );
  await cdp.send("Page.navigate", { url }, s);
  await waitFor(cdp, s, "document.readyState === 'complete'", { label: `${shot.id} load` });
  await waitFor(
    cdp,
    s,
    "!document.querySelector('[aria-busy=\"true\"]')",
    { timeout: 20000, label: `${shot.id} boot skeleton` },
  );
  await waitFor(cdp, s, "(window.__inflight?.() ?? 0) === 0", {
    timeout: 20000,
    label: `${shot.id} in-flight requests`,
  });
  if (shot.settle) await new Promise((r) => setTimeout(r, shot.settle));
  await settle(cdp, s);
  let last = -1;
  for (let i = 0; i < 6; i++) {
    const h = await evaluate(cdp, s, "document.documentElement.scrollHeight");
    if (h === last) break;
    last = h;
    await new Promise((r) => setTimeout(r, 140));
  }
}

main().catch((e) => {
  console.error(`\n✗ ${e.message}\n`);
  process.exit(1);
});
