#!/usr/bin/env bash
# Install the launchd agent that keeps MyMacros fed (#19, #20).
#
#   MYMACROS_SYNC_TOKEN=mms_… ./tools/install-sync-agent.sh
#   ./tools/install-sync-agent.sh --uninstall
#
# The token is read from the environment and written into the agent's own
# plist, which is then chmod 600. It is never passed as an argument (arguments
# are visible in `ps` to every process on the machine) and never committed —
# the plist lives in ~/Library/LaunchAgents, not in this repo.
#
# Runs both syncs on one schedule: runs from debrief's SQLite, and weigh-ins
# from Garmin. Both are idempotent — they re-send a rolling window and the
# endpoint upserts — so a missed run costs nothing and a double run writes
# nothing twice. That is what makes a blind 30-minute timer the right shape
# rather than something that has to track what it last sent.
set -euo pipefail

LABEL="run.debrief.mymacros-sync"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$HOME/Library/Logs/mymacros"

if [[ "${1:-}" == "--uninstall" ]]; then
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  rm -f "$PLIST"
  echo "Removed $LABEL."
  exit 0
fi

if [[ -z "${MYMACROS_SYNC_TOKEN:-}" ]]; then
  echo "MYMACROS_SYNC_TOKEN is not set." >&2
  echo "Issue one at https://fuel.debrief.run → Settings → Sync, then:" >&2
  echo "  MYMACROS_SYNC_TOKEN=mms_… $0" >&2
  exit 2
fi

command -v uv >/dev/null || { echo "uv is required for the Garmin half." >&2; exit 2; }
mkdir -p "$LOG_DIR" "$(dirname "$PLIST")"

# A wrapper, because launchd runs one program and we have two syncs. Written
# beside the plist rather than into the repo: it is machine-local
# configuration, and it carries a path that only makes sense here.
RUNNER="$HOME/Library/Application Support/mymacros-sync.sh"
mkdir -p "$(dirname "$RUNNER")"
cat > "$RUNNER" <<RUNNER_EOF
#!/usr/bin/env bash
# Generated by tools/install-sync-agent.sh — edit that, not this.
#
# No 'set -e': the two syncs are independent, and Garmin being down should
# never stop the runs from arriving.
#
# But independence is not the same as silence (#62). The old version ended
# each line with \`|| echo\`, which swallowed the status — so launchd recorded
# \`last exit code = 0\` across a run history that included sixteen consecutive
# Garmin failures and two Cloudflare 403s. A permanently-green health signal
# is worse than no health signal. Failures are collected and re-raised at the
# end, after both syncs have had their turn.
status=0

# A repo that has moved is itself a silent failure: without this the script
# would carry on in the wrong directory and sync nothing, successfully.
cd "$REPO" || { echo "!! repo not found at $REPO"; exit 1; }

run_sync() {
  local label=\$1
  shift
  echo "--- \$(date -Iseconds) \$label ---"

  # Captured on the same line as the call, not read from \$? afterwards: a
  # compound \`if\` with no else branch returns 0 when its condition fails, so
  # \$? after the fi is the *if statement's* status and always reported
  # "exit 0". Caught by breaking this on purpose.
  local rc=0
  "\$@" || rc=\$?
  (( rc == 0 )) && return 0

  # to stdout as well as the failing command's stderr, so one file carries the
  # whole story in order
  echo "!! \$label sync FAILED (exit \$rc)"
  status=1
}

run_sync runs   /usr/bin/env node tools/sync-runs.mjs --days 30
run_sync garmin /usr/bin/env uv run tools/sync-garmin.py --days 30

# Keep one previous generation. launchd opens the log fresh on each launch, so
# rotating after the run is what makes the rename land cleanly: this run's
# output is complete, and the next invocation starts a new file.
if [[ -f "$LOG_DIR/sync.log" ]]; then
  size=\$(stat -f%z "$LOG_DIR/sync.log" 2>/dev/null || echo 0)
  if (( size > 1048576 )); then
    rm -f "$LOG_DIR/sync.log.1"
    mv "$LOG_DIR/sync.log" "$LOG_DIR/sync.log.1"
  fi
fi

exit \$status
RUNNER_EOF
chmod 700 "$RUNNER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$RUNNER</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>MYMACROS_SYNC_TOKEN</key><string>$MYMACROS_SYNC_TOKEN</string>
    <!-- launchd starts with a minimal PATH that has neither Homebrew nor uv -->
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartInterval</key><integer>1800</integer>
  <!-- once at load, so a fresh install proves itself immediately rather than
       in half an hour -->
  <key>RunAtLoad</key><true/>
  <!-- One file, deliberately (#62). These were split, and every REFUSED,
       REJECTED and "sync failed" line landed in sync.err.log while the
       installer's closing advice pointed at sync.log — so two real outages sat
       unread in a file nobody had been told about. Interleaved in order, one
       tail tells the whole story. -->
  <key>StandardOutPath</key><string>$LOG_DIR/sync.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/sync.log</string>
</dict>
</plist>
PLIST_EOF

# The plist holds a live credential.
chmod 600 "$PLIST"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "Installed $LABEL — every 30 minutes, and once now."
echo "  log:       $LOG_DIR/sync.log  (rotates at 1MB, keeps one generation)"
echo "  uninstall: $0 --uninstall"
echo
echo "Confirm it ran:   tail -20 $LOG_DIR/sync.log"
echo "Confirm it works: launchctl print gui/$(id -u)/$LABEL | grep 'last exit code'"
echo
echo "That exit code is now real — a failing sync reports non-zero rather than"
echo "reporting success into a log nobody reads (#62)."

if [[ -f "$LOG_DIR/sync.err.log" ]]; then
  echo
  echo "Note: $LOG_DIR/sync.err.log is from the old split-log setup and is no"
  echo "longer written. Worth reading once before deleting it — that is where"
  echo "the failures used to go."
fi
