#!/usr/bin/env bash
# Install the launchd agent that keeps MyMacros fed (#19, #20).
#
#   MYMACROS_SYNC_TOKEN=mms_… ./tools/install-sync-agent.sh
#   ./tools/install-sync-agent.sh --uninstall
#
# The token is read from the environment and written into the agent's own
# plist, which is then chmod 600. It is never passed as an argument (arguments
# are visible in `ps` to every process on the machine) and never committed —
# the plist lives in ~/Library/LaunchAgents, not in this repo.
#
# Runs both syncs on one schedule: runs from debrief's SQLite, and weigh-ins
# from Garmin. Both are idempotent — they re-send a rolling window and the
# endpoint upserts — so a missed run costs nothing and a double run writes
# nothing twice. That is what makes a blind 30-minute timer the right shape
# rather than something that has to track what it last sent.
set -euo pipefail

LABEL="run.debrief.mymacros-sync"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$HOME/Library/Logs/mymacros"

if [[ "${1:-}" == "--uninstall" ]]; then
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  rm -f "$PLIST"
  echo "Removed $LABEL."
  exit 0
fi

if [[ -z "${MYMACROS_SYNC_TOKEN:-}" ]]; then
  echo "MYMACROS_SYNC_TOKEN is not set." >&2
  echo "Issue one at https://fuel.debrief.run → Settings → Sync, then:" >&2
  echo "  MYMACROS_SYNC_TOKEN=mms_… $0" >&2
  exit 2
fi

command -v uv >/dev/null || { echo "uv is required for the Garmin half." >&2; exit 2; }
mkdir -p "$LOG_DIR" "$(dirname "$PLIST")"

# A wrapper, because launchd runs one program and we have two syncs. Written
# beside the plist rather than into the repo: it is machine-local
# configuration, and it carries a path that only makes sense here.
RUNNER="$HOME/Library/Application Support/mymacros-sync.sh"
mkdir -p "$(dirname "$RUNNER")"
cat > "$RUNNER" <<RUNNER_EOF
#!/usr/bin/env bash
# Generated by tools/install-sync-agent.sh — edit that, not this.
# No 'set -e': the two syncs are independent, and Garmin being down should
# never stop the runs from arriving.
cd "$REPO"
echo "--- \$(date -Iseconds) runs ---"
/usr/bin/env node tools/sync-runs.mjs --days 30 || echo "runs sync failed (\$?)"
echo "--- \$(date -Iseconds) garmin ---"
/usr/bin/env uv run tools/sync-garmin.py --days 30 || echo "garmin sync failed (\$?)"
RUNNER_EOF
chmod 700 "$RUNNER"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$RUNNER</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>MYMACROS_SYNC_TOKEN</key><string>$MYMACROS_SYNC_TOKEN</string>
    <!-- launchd starts with a minimal PATH that has neither Homebrew nor uv -->
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartInterval</key><integer>1800</integer>
  <!-- once at load, so a fresh install proves itself immediately rather than
       in half an hour -->
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>$LOG_DIR/sync.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/sync.err.log</string>
</dict>
</plist>
PLIST_EOF

# The plist holds a live credential.
chmod 600 "$PLIST"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "Installed $LABEL — every 30 minutes, and once now."
echo "  logs:      $LOG_DIR/sync.log"
echo "  errors:    $LOG_DIR/sync.err.log"
echo "  uninstall: $0 --uninstall"
echo
echo "Confirm it ran:  tail -20 $LOG_DIR/sync.log"
